import type { Member, Event, Contribution } from './types';

export const members: Member[] = [
  {
    id: 'm1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    phone: '123-456-7890',
    status: 'Active',
    birthday: '1990-05-15',
    photoUrl: 'https://picsum.photos/seed/m1/200/200',
    notes: 'Long-time member, volunteers in the youth group.',
  },
  {
    id: 'm2',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    phone: '987-654-3210',
    status: 'Active',
    birthday: '1985-08-22',
    photoUrl: 'https://picsum.photos/seed/m2/200/200',
    notes: 'Leads the choir. Allergic to peanuts.',
  },
  {
    id: 'm3',
    firstName: 'Peter',
    lastName: 'Jones',
    email: 'peter.jones@example.com',
    phone: '555-123-4567',
    status: 'Prospect',
    birthday: '2001-01-30',
    photoUrl: 'https://picsum.photos/seed/m3/200/200',
    notes: 'New to the area, attended the last three services.',
  },
  {
    id: 'm4',
    firstName: 'Mary',
    lastName: 'Williams',
    email: 'mary.w@example.com',
    phone: '555-987-6543',
    status: 'Active',
    birthday: '1978-11-11',
    photoUrl: 'https://picsum.photos/seed/m4/200/200',
    notes: '',
  },
  {
    id: 'm5',
    firstName: 'David',
    lastName: 'Brown',
    email: 'david.b@example.com',
    phone: '555-456-1230',
    status: 'Archived',
    birthday: '1965-03-03',
    photoUrl: 'https://picsum.photos/seed/m5/200/200',
    notes: 'Moved to another state in 2022.',
  },
];

export const events: Event[] = [
  {
    id: 'e1',
    title: 'Sunday Service',
    date: new Date(new Date().setDate(new Date().getDate() - new Date().getDay())),
    description: 'Weekly Sunday worship service.',
  },
  {
    id: 'e2',
    title: 'Youth Group Meeting',
    date: new Date(new Date().setDate(new Date().getDate() + 3)),
    description: 'Fun and fellowship for teens.',
  },
  {
    id: 'e3',
    title: 'Community Bake Sale',
    date: new Date(new Date().setDate(new Date().getDate() + 12)),
    description: 'Fundraiser for the new community center.',
  },
];

export const contributions: Contribution[] = [
  {
    id: 'c1',
    memberId: 'm1',
    memberName: 'John Doe',
    amount: 100,
    category: 'Tithes',
    date: new Date(new Date().setDate(new Date().getDate() - 5)),
  },
  {
    id: 'c2',
    memberId: 'm2',
    memberName: 'Jane Smith',
    amount: 50,
    category: 'Offering',
    date: new Date(new Date().setDate(new Date().getDate() - 5)),
  },
  {
    id: 'c3',
    memberId: 'm4',
    memberName: 'Mary Williams',
    amount: 250,
    category: 'Donation',
    date: new Date(new Date().setDate(new Date().getDate() - 10)),
  },
  {
    id: 'c4',
    memberId: 'm1',
    memberName: 'John Doe',
    amount: 20,
    category: 'Other',
    date: new Date(new Date().setDate(new Date().getDate() - 12)),
  },
  {
    id: 'c5',
    memberId: 'm2',
    memberName: 'Jane Smith',
    amount: 150,
    category: 'Tithes',
    date: new Date(new Date().setDate(new Date().getDate() - 12)),
  },
];
